spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot  
    username: postgres
    password: postgres  
    initialization-mode: always
#    schema: classpath:/schema.sql
#    data: classpath:/data.sql
    continue-on-error: true
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090

jwt:
  secret: jwtsec
  expire: 60000
  refresh:
    expire: 120000
  get:
    token:
      uri: /authenticate
